### ISSUE TITLE
Section 2.6 Live Linear Streaming

### ISSUE THREAD

**Issue by boyofgreen** [w3c/webmediaguidelines#15]
This area is being worked by Andy Beach (ms), and draft will be posted here for content.

**Comment by thasso** [comment]
@boyofgreen or Andy, could you maybe add a short bullet point list summarising what you are planing to add to this section? Since I am working on #14 I would like to see how the two sections would eventually align.

**Comment by andybeach** [comment]
Yes, I’ll add a list today or tomorrow.

**Comment by andybeach** [comment]
posting this here for now as I'm running between meetings.  topics for live linear I though needed to be covered were:

	1) Differs from VOD and Live in that content is ingested from satellite, fiber, or IP and streamed in real-time (similar workflow to traditional cable channel).  Steam is generally multiple shows streamed in one long continuous session, not individually streamed programs.
	2) Content will be delivered from CDN
	3) Content will vary from SD to HD and some UHD (future looking)
		a. Single stream may have different resolutions as one program ends and a new one begins - rare, but possible
	4) Content will categorically be ABR based and have several of the following:
		a. Rights Management or Encryption
		b. Customized Manifest/Playlist files that incorporate Closed Captions, Digital Ad Insertion (DAI), Live to VOD 
                c. Instream metadata such as SCTE-35, Nielson ID3 tags, content and geo blackouts

**Comment by joelkorpi** [comment]
Hey Andy, we removed this section because there was no content submitted yet but if you have content please add the section back into 2 and open a PR! @andybeach

**Comment by andybeach** [comment]
Sounds good

This email was typed in front of a live studio audience.

On Aug 28, 2017, at 8:27 AM, Joel Korpi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Andy, we removed this section because there was no content submitted yet but if you have content please add the section back into 2 and open a PR! @andybeach<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fandybeach&data=02%7C01%7CAndy.Beach%40microsoft.com%7Cb6e73b5a3c034028364408d4ee294a37%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636395308501892130&sdata=DGZK99ODfNGdQJxtG5w9rq6B9rcAGpJ%2Bls3gAi%2BBx8E%3D&reserved=0>

**Comment by thasso** [comment]
@joelkorpi should we still try to do something about this one or maybe move it to v2 ?

**Comment by joelkorpi** [comment]
I vote move it to v2 @thasso
